version: '2'
services:
  app:
    build: .
    container_name: project-system-app
    image: project-system
    ports:
      - '3000:3000'
    command: "/bin/sh -c 'npm install && sleep infinity'"
    volumes:
      - unison-server:/app:nocopy
    links:
        - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

volumes:
  unison-server:
    external: true


