version: '2'
services:
  app:
    build: .
    container_name: project-system-app
    image: project-system
    ports:
      - '3000:3000'
    restart: always
    command: "/bin/sh -c 'npm run build && npm start'"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

